# Generated by Django 4.2.11 on 2024-04-13 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('result', models.IntegerField()),
                ('search_period', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trends.keyword')),
            ],
        ),
    ]
